// Generated by Haxe
(function () { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); };
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var Editor = function(root) {
	this.root = root;
};
Editor.__name__ = true;
Editor.create = function(id,schema) {
	var tmp;
	switch(schema[1]) {
	case 0:
		tmp = new StringEditor(id);
		break;
	case 2:
		tmp = new ObjectEditor(id,schema[2]);
		break;
	case 1:
		tmp = new StringChoiceEditor(id,schema[2]);
		break;
	}
	return tmp;
};
Editor.prototype = {
	setValue: function(value) {
		throw new js__$Boot_HaxeError("not implemented");
	}
	,getValue: function() {
		throw new js__$Boot_HaxeError("not implemented");
	}
};
var StringEditor = function(id) {
	var tmp;
	var _this = window.document;
	tmp = _this.createElement("input");
	this.input = tmp;
	this.input.id = id;
	this.input.type = "text";
	Editor.call(this,this.input);
};
StringEditor.__name__ = true;
StringEditor.__super__ = Editor;
StringEditor.prototype = $extend(Editor.prototype,{
	setValue: function(value) {
		this.input.value = value;
	}
	,getValue: function() {
		return this.input.value;
	}
});
var StringChoiceEditor = function(id,choices) {
	this.choices = choices;
	this.elems = new haxe_ds_StringMap();
	var tmp;
	var _this = window.document;
	tmp = _this.createElement("div");
	var div = tmp;
	div.id = id;
	Editor.call(this,div);
	var _g = 0;
	while(_g < choices.length) {
		var choice = choices[_g];
		++_g;
		var tmp1;
		var _this1 = window.document;
		tmp1 = _this1.createElement("label");
		var row = tmp1;
		var tmp2;
		var _this2 = window.document;
		tmp2 = _this2.createElement("input");
		var radio = tmp2;
		radio.type = "radio";
		radio.name = id;
		var tmp3;
		var _this3 = this.elems;
		if(__map_reserved[choice] != null) _this3.setReserved(choice,radio); else _this3.h[choice] = radio;
		tmp3 = radio;
		tmp3;
		row.appendChild(radio);
		var label = window.document.createTextNode(choice);
		row.appendChild(label);
		div.appendChild(row);
	}
};
StringChoiceEditor.__name__ = true;
StringChoiceEditor.__super__ = Editor;
StringChoiceEditor.prototype = $extend(Editor.prototype,{
	setValue: function(value) {
		var $it0 = this.elems.keys();
		while( $it0.hasNext() ) {
			var choice = $it0.next();
			var tmp;
			var _this = this.elems;
			if(__map_reserved[choice] != null) tmp = _this.getReserved(choice); else tmp = _this.h[choice];
			tmp.checked = choice == value;
		}
	}
	,getValue: function() {
		var $it0 = this.elems.keys();
		while( $it0.hasNext() ) {
			var choice = $it0.next();
			var tmp;
			var _this = this.elems;
			if(__map_reserved[choice] != null) tmp = _this.getReserved(choice); else tmp = _this.h[choice];
			if(tmp.checked) return choice;
		}
		window.console.warn("No value checked");
		return null;
	}
});
var ObjectEditor = function(id,fields) {
	var tmp;
	var _this = window.document;
	tmp = _this.createElement("div");
	var div = tmp;
	div.id = id;
	Editor.call(this,div);
	this.editors = new haxe_ds_StringMap();
	var _g = 0;
	while(_g < fields.length) {
		var field = fields[_g];
		++_g;
		var tmp1;
		var _this1 = window.document;
		tmp1 = _this1.createElement("div");
		var row = tmp1;
		div.appendChild(row);
		var editorId = id + "-" + field.name;
		var tmp2;
		var _this2 = window.document;
		tmp2 = _this2.createElement("label");
		var label = tmp2;
		label.innerText = field.name;
		label.setAttribute("for",editorId);
		row.appendChild(label);
		var editor = Editor.create(editorId,field.type);
		row.appendChild(editor.root);
		var tmp3;
		var _this3 = this.editors;
		var key = field.name;
		if(__map_reserved[key] != null) _this3.setReserved(key,editor); else _this3.h[key] = editor;
		tmp3 = editor;
		tmp3;
	}
};
ObjectEditor.__name__ = true;
ObjectEditor.__super__ = Editor;
ObjectEditor.prototype = $extend(Editor.prototype,{
	setValue: function(value) {
		var _g = 0;
		var _g1 = Reflect.fields(value);
		while(_g < _g1.length) {
			var field = _g1[_g];
			++_g;
			var tmp;
			var _this = this.editors;
			if(__map_reserved[field] != null) tmp = _this.getReserved(field); else tmp = _this.h[field];
			var editor = tmp;
			if(editor == null) {
				window.console.warn("No editor for field " + field);
				continue;
			}
			editor.setValue(Reflect.field(value,field));
		}
	}
	,getValue: function() {
		var result = { };
		var $it0 = this.editors.keys();
		while( $it0.hasNext() ) {
			var field = $it0.next();
			var tmp;
			var _this = this.editors;
			if(__map_reserved[field] != null) tmp = _this.getReserved(field); else tmp = _this.h[field];
			var value = tmp.getValue();
			result[field] = value;
		}
		return result;
	}
});
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	var schema = Schema.VObject([{ name : "name", type : Schema.VString},{ name : "type", type : Schema.VStringChoice(["hq","post","turret"])},{ name : "coords", type : Schema.VObject([{ name : "x", type : Schema.VString},{ name : "y", type : Schema.VString}])}]);
	window.onload = function() {
		var container = window.document.getElementById("container");
		var editor = Editor.create("root",schema);
		editor.setValue({ name : "House", type : "post", coords : { x : 10, y : 15}});
		container.appendChild(editor.root);
		window.document.getElementById("submit").onclick = function() {
			console.log(editor.getValue());
		};
	};
};
Math.__name__ = true;
var Reflect = function() { };
Reflect.__name__ = true;
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		return null;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) a.push(f);
		}
	}
	return a;
};
var Schema = { __ename__ : true, __constructs__ : ["VString","VStringChoice","VObject"] };
Schema.VString = ["VString",0];
Schema.VString.toString = $estr;
Schema.VString.__enum__ = Schema;
Schema.VStringChoice = function(choices) { var $x = ["VStringChoice",1,choices]; $x.__enum__ = Schema; $x.toString = $estr; return $x; };
Schema.VObject = function(fields) { var $x = ["VObject",2,fields]; $x.__enum__ = Schema; $x.toString = $estr; return $x; };
var haxe_IMap = function() { };
haxe_IMap.__name__ = true;
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = true;
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) this.rh = { };
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		return this.rh == null?null:this.rh["$" + key];
	}
	,keys: function() {
		var tmp;
		var _this = this.arrayKeys();
		tmp = HxOverrides.iter(_this);
		return tmp;
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) out.push(key);
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) out.push(key.substr(1));
			}
		}
		return out;
	}
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) Error.captureStackTrace(this,js__$Boot_HaxeError);
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) return "null";
	if(s.length >= 5) return "<...>";
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) t = "object";
	switch(t) {
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) return o[0];
				var str2 = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i1 = _g1++;
					if(i1 != 2) str2 += "," + js_Boot.__string_rec(o[i1],s); else str2 += js_Boot.__string_rec(o[i1],s);
				}
				return str2 + ")";
			}
			var l = o.length;
			var i;
			var str1 = "[";
			s += "\t";
			var _g2 = 0;
			while(_g2 < l) {
				var i2 = _g2++;
				str1 += (i2 > 0?",":"") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			if (e instanceof js__$Boot_HaxeError) e = e.val;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") return s2;
		}
		var k = null;
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) str += ", \n";
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "function":
		return "<function>";
	case "string":
		return o;
	default:
		return String(o);
	}
};
String.__name__ = true;
Array.__name__ = true;
var __map_reserved = {}
Main.main();
})();
